### ISSUE TITLE
Crash on otherwise vanilla 1.12.1 profile

### ISSUE THREAD

**Issue by Xechon** [coolsquid/MiscTweaks#1]
https://pastebin.com/MswhCHpH

Game window doesn't even get a chance to open, the launcher quickly crashes due to an asm transformer using an invalid class def: net.minecraft.block.BlockFire

**Comment by coolsquid** [comment]
Seems like I forgot to update some mappings. Should be an easy fix.

**Comment by coolsquid** [comment]
Try version [1.1.4](https://github.com/coolsquid/MiscTweaks/releases/tag/v1.1.4).

**Comment by Xechon** [comment]
Working now, thanks!
