### ISSUE TITLE
Unable to change starvation damage

### ISSUE THREAD

**Issue by NielsPilgaard** [coolsquid/MiscTweaks#2]
Hey!

Minecraft 1.12.1
Forge 1.12.1-14.22.1.2485
MiscTweaks-1.12-1.1.4

I changed starvation damage from 1 to 10, but it still only did 1 damage. I fully restarted the game. 
Also, the starvation config doesn't show in the in-game GUI, I thought that might be related :)

**Comment by coolsquid** [comment]
The starvation tweaks depend on [AppleCore](https://minecraft.curseforge.com/projects/applecore).

**Comment by NielsPilgaard** [comment]
AppleCore was installed.

**Comment by coolsquid** [comment]
That's odd. I'll look into it.

**Comment by coolsquid** [comment]
The issue has been resolved, and a new version will be uploaded to GitHub and CurseForge shortly.

**Comment by NielsPilgaard** [comment]
Thank you :)
